### ISSUE TITLE
动态 Form 删减表单问题反馈

### ISSUE THREAD

**Issue by wangyahua** [XiaoMi/hiui#1521]
**Bug 描述**
清晰简洁的描述 bug 内容。
动态Form表单删减Select异步选择数据后，进行删除的时候会清空所选内容。

**参考**
重现步骤：
1. 使用 FormList  组件
2. 点击 'remove' 方法

**预期行为**
清晰简洁的描述应当产生的效果。
正确删除后，不清除其他Select的值。

**截屏**
如果方便的话可以提供一个截屏描述你的问题。

![image](https://user-images.githubusercontent.com/20548874/104702149-8b3d9080-5750-11eb-9511-244f8c20000e.png)

**可重现环境：**
 - 系统： [比如 windows]
 - 浏览器： [比如 chrome,]
 - HIUI 的版本： [比如 3.3.0]

**附加内容**
import React from 'react'
    import { Grid, Button, Radio, Input, Form } from '@hi-ui/hiui'

    class Demo extends React.Component {
      constructor() {
        super()
        this.form = React.createRef()
        this.state = {
          initialValues:{
            phone:'123',
            testList:[{first: "123",last: "rrr"}]
          },
          rules: {
            name: {
              required: true,
              message: <span style={{color: '#ccc'}}>请输入名称</span>,
              trigger: 'onBlur,onChange'
            },
            region: {
              required: true,
              message: '请选择区域',
              trigger: 'onChange'
            },
            count: {
              required: true,
              trigger: 'onChange',
              validator: (rule, value, cb) => {
                const count = +value
                if(isNaN(count)) {
                  cb('请输入数字')
                } else if(count <= 0) {
                  cb('必须是正数')
                } else {
                  cb()
                }
              }
            }
          }
        }
      }

      handleSubmit() {
        this.form.current.validate((valid,error) => {
          if(!error) {
            console.log(valid)
            alert('submit')
          } else {
            console.log('error',error)
            return false
          }
        })
      }

      cancelSubmit() {
        this.setState({
          form: {
            name: '',
            region: '',
            count: ''
          }
        })
        this.form.current.resetValidates()
      }

      render(){
        const Row = Grid.Row
        const Col = Grid.Col
        const FormItem = Form.Item
        const FormList = Form.List
        const FormSubmit = Form.Submit
        const FormReset = Form.Reset

        return (
            <Row>
            <Col span={12}>
              <Form
                ref={this.form}
                initialValues={this.state.initialValues}
                rules={this.state.rules}
                labelWidth='80'
                labelPlacement='right'
                onValuesChange={(changedValues, allValues) => {
                  console.log(
                    'changedValues:',
                    changedValues,
                    'allValues:',
                    allValues
                  )
                }}
              >
              <FormItem
              label='账号'
              field={"phone"}
              rules={{
              trigger:'onChange',
              type:'number',
              required:true,
              validator: (rule,value,callback) => {
                const telReg = /^[1][3|4|5|6|7|8|9][0-9]{9}$/
                if(!value){
                  callback("请输入手机号")
                } else if (!telReg.test(value)){
                  callback("请输入正确的手机号")
                } else {
                  callback()
                }
              },
              }}>
              <Input placeholder='请输入手机号' />
            </FormItem>
                <FormList name='testList'>
                  {(fields, { add, remove }) => {
                    return (
                      <div className='list'>
                        {fields.map((field, index) => (
                          <div style={{ display: 'flex' }} key={index}>
                            <FormItem
                              {...field}
                              name = 'first'
                            >
                              <Select
                                type='single'
                                dataSource={{
                                  method: 'GET',
                                  key: 'id',
                                  url: 'https://mife-gallery.test.mi.com/hiui/stores',
                                  transformResponse: (res) => {
                                    if(res.code === 200){
                                      return res.data
                                    }
                                    return []
                                  }
                                }}
                                placeholder='请选择'
                                style={{ width: 200 }}
                                onChange={(item) => {
                                  
                                }}
                              />
                            </FormItem>
                            <FormItem
                              {...field}
                              labelWidth='0'
                              name = 'last'
                            >
                              <Input placeholder='请输入' style={{width:'200px'}}/>
                            </FormItem>
                            <Icon
                              name='close'
                              style={{
                                color: '#999',
                                fontSize: '16px',
                                cursor: 'pointer',
                                height:'18px',
                                marginTop:'4px',
                              }}
                              onClick={() => {
                                remove(field)
                              }}
                            />
                          </div>
                        ))}
                        <div style={{
                            marginLeft: '80px',
                            width: "200px",
                            textAlign: "center",
                            border: '1px dashed #ccc',
                            borderRadius: '2px',
                            marginBottom: '24px',
                        }}>
                          <Button
                            type='line'
                            appearance='link'
                            icon='plus'
                            onClick={() => {
                              add()
                            }}
                          >
                            添加选项
                          </Button>
                        </div>
                      </div>
                    )
                  }}
                </FormList>

                <FormItem>
                  <FormSubmit
                    type='primary'
                    onClick={(values, errors) => {
                      console.log('Get form value:', values, errors)
                    }}
                  >
                    提交
                  </FormSubmit>
                  <FormReset
                    type='line'
                    onClick={() => {
                      console.log('reset form')
                    }}
                  >
                    重置
                  </FormReset>
                  <Button type="primary" appearance="link" onClick={()=>{
                    console.log('填充表单')
                    this.form.current.setFieldsValue({
                      testList:[
                        {
                          first: "123",
                          last: "rrr"
                        }]
                    })
                }}>fill Form</Button>
                </FormItem>
              </Form>
            </Col>
          </Row>
        )
      }
    }

**Comment by Flcwl** [comment]
@wangyahua 对于需要删减的动态列表，需要注意 `key` 唯一性，建议使用后端下发的 `id` 之类的唯一标识，不建议使用数组的下标。可更改如下代码：
```js
                        {fields.map((field, index) => (
-                          <div style={{ display: 'flex' }} key={index}>
+                          <div style={{ display: 'flex' }} key={field.field}>
                            <FormItem
                              {...field}
                              name = 'first'
```
