### ISSUE TITLE
DatePicker 在Form.Item 中点击清空Icon无效

### ISSUE THREAD

**Issue by wugaoliang1116** [XiaoMi/hiui#1524]
![image](https://user-images.githubusercontent.com/24740506/104864668-a5f04f00-5974-11eb-94bd-a6b1899b7138.png)

**Comment by ksblklu** [comment]
SelectTree在Form.Item包裹下，清空按钮存在同样问题
![image](https://user-images.githubusercontent.com/27538066/104900467-0dc78980-59b7-11eb-8a86-e4f33eecc5b7.png)
