### ISSUE TITLE
省市区三级联动组件

### ISSUE THREAD

**Issue by ityangs** [XiaoMi/hiui#1538]
**你期望的功能是否与某种使用上的困难相关？如果是请描述一下**
可以提供统一的省市区三级联动组件吗，现在使用率还是比较高的

**Comment by sivan** [comment]
这类跟数据相关的感觉更适合基于选择器组件封装成业务组件来使用？因为不同的业务场景，对省市区的定义不一样（行政范围、配送范围、维修范围）。在组件库里做，只能做一个示例，并且会把数据结构定死。应用实际的接口时还要对数据再做适配。
