### ISSUE TITLE
关于低代码平台或者编辑器开发的图标库

### ISSUE THREAD

**Issue by snake89322** [XiaoMi/hiui#1554]
**你期望的功能是否与某种使用上的困难相关？如果是请描述一下**
清晰简洁的描述一下你遇到的问题，例如：当我 [...] 总是困扰应该如何 [...]
目前需要补全一些编辑器相关开发的图标，比如 撤回 恢复 格式化 更多等
可参考 www.processon.com 的编辑器图标。

**描述你期待的解决方案**
清晰简洁的描述一下你期望的行为。
图标库的更新和增加

**描述你考虑的其它形式**
清晰简洁的描述你考虑过的其它解决方式或实现功能。

**附加信息**
关于你的功能需求的任何附加信息或截图说明等。

**Comment by solarjoker** [comment]
done
