### ISSUE TITLE
文档部分链接 404

### ISSUE THREAD

**Issue by solarjoker** [XiaoMi/hiui#1565]
https://xiaomi.github.io/hiui/zh-CN/components/grid，像这种链接，刷新都会 404

**Comment by harry-xiaomi** [comment]
+1，截图如下 https://xiaomi.github.io/hiui/zh-CN/components/grid

<img width="736" alt="screen" src="https://user-images.githubusercontent.com/47099356/113824542-84a04180-97b2-11eb-8dac-49f5d96f5178.png">

**Comment by youngBrain1893** [comment]
纯静态页面，history router 无法正常加载到资源 🤣
