### ISSUE TITLE
表头吸顶时，表格内容滚动问题

### ISSUE THREAD

**Issue by ksblklu** [XiaoMi/hiui#1596]
**Bug 描述**
HIUI2.15 ，
设置表头吸顶时，滚动表格内容，导致数据量小的分页内容滚动至可视区域上方，用户无法看见数据
**参考**
重现步骤：
1. 使用Table组件， table数据共有101条，分两页展示，每页pageSize为100条
2. 加载第一页数据（共有100条），向上滚动表格数据
3. 点击第二页（1条数据）
4. 此时第二页的内容因为第一页的滚动动作滚动至可视区域外，需要向下滚动才能看见

**预期行为**
数据更新时将数据重新滚动至可视区域

**截屏**
![image](https://user-images.githubusercontent.com/27538066/108340041-207dea00-7213-11eb-8d3b-2fa82107d1df.png)

**Comment by wugaoliang1116** [comment]
现 Table 不再 **进行维护** ，我们将 Table 就行了重写并已发布，暂命名为[hi-table](https://github.com/hiui-group/hi-table)，已在 HiUI 3.x 进行了集成
