### ISSUE TITLE
Tree树形控件Bug

### ISSUE THREAD

**Issue by Tianjieshao** [XiaoMi/hiui#1634]
**Bug 描述**
Tree树形控件，从外部界面跳转到树形控件展示界面后，子节点默认全部选中，但是父节点未默认勾选

**预期行为**
后端传递回数据，默认子组件全部选中时，父组件的值也应该默认选中

**截屏**
![image](https://user-images.githubusercontent.com/42732135/110077484-2d790c80-7dc1-11eb-991b-6a67daf0ad90.png)

**可重现环境：**
 - 系统： [windows]
 - 浏览器： [chrome]
 - HIUI 的版本： [2.15.8]

**Comment by solarjoker** [comment]
您好，这个不是bug，tree 的选中是完全受控的，即你传哪个选中的节点我们选中哪个节点，不会去帮您自动处理选中逻辑。
