### ISSUE TITLE
FormItem中，Input默认值没有正确显示

### ISSUE THREAD

**Issue by ksblklu** [XiaoMi/hiui#1643]
版本：HiUI3.5.0
`import React from 'react'
  import { Form, Grid, Radio, Button, Input } from '@hi-ui/hiui'

    class Demo extends React.Component {  
      constructor(props){
        super(props)
        this.state = {
          phone: ''
        }
        this.form = React.createRef()
      }
      render (){
        const FormItem = Form.Item
        const { phone } = this.state
        return (
          <Form labelWidth='70' labelPlacement='left'>
            <FormItem label='手机号'>
              <Input placeholder={'请输入'} value={phone}/>
            </FormItem>
      </Form>
        )
      }
    }`
input框内内容没有正确设置
![image](https://user-images.githubusercontent.com/27538066/111111724-d41b9500-8599-11eb-8c79-34fb9208c8cf.png)

**Comment by wugaoliang1116** [comment]
v3 版的 Form 中FormItem包裹的元素的value属性值由Form进行内部值控制；不再由用户进行对值进行受控；方便表单值的整体管理
