### ISSUE TITLE
穿梭框的拖动排序功能，可以完善一下，没有拖动的回调函数，拖动之后想让targetIds这个数组重新排序

### ISSUE THREAD

**Issue by yujing19951209** [XiaoMi/hiui#1661]
**你期望的功能是否与某种使用上的困难相关？如果是请描述一下**
清晰简洁的描述一下你遇到的问题，例如：当我 [...] 总是困扰应该如何 [...]

**描述你期待的解决方案**
清晰简洁的描述一下你期望的行为。

**描述你考虑的其它形式**
清晰简洁的描述你考虑过的其它解决方式或实现功能。

**附加信息**
关于你的功能需求的任何附加信息或截图说明等。

**Comment by wugaoliang1116** [comment]
![image](https://user-images.githubusercontent.com/24740506/113795662-ff039e00-977f-11eb-9268-404000b3f547.png)
