### ISSUE TITLE
hiui 2.0 Dropdown 下拉菜单  change 时修改了原数据

### ISSUE THREAD

**Issue by 738326776zby** [XiaoMi/hiui#1751]
hiui 2.0 Dropdown 下拉菜单  change 时修改了原数据
**参考**
重现步骤：
1. 使用 Dropdown 组件
2. 使用Select 组件,并且数据源使用同一份
3. Dropdow change 选中其他值 ，select change 选中其他值
4. select 中的数据被修复，前端交互报错 ，选中的值变成 [Object,Object]

**Comment by wugaoliang1116** [comment]
2.15.10
