### ISSUE TITLE
LegacyTree

### ISSUE THREAD

**Issue by duanwenxiang** [XiaoMi/hiui#1758]
**Bug 描述**
滚动距离没有计算在内

**参考**
重现步骤：
在滚动情况下编辑，input 移位

**截屏**
正常情况下
![image](https://user-images.githubusercontent.com/46153686/120437402-9cf79b80-c3b2-11eb-994f-67846019737d.png)
滚动后
![image](https://user-images.githubusercontent.com/46153686/120437518-bd275a80-c3b2-11eb-8d77-0551fe4ff17c.png)

**Comment by solarjoker** [comment]
done
