### ISSUE TITLE
react-router匹配路由时，对于相似路径匹配后，匹配成功后未停止匹配，按照上图路由规则，会匹配到两次PlanInputForm组件的渲染。

### ISSUE THREAD

**Issue by peng92055** [XiaoMi/hiui#1773]
**Bug 描述**
react-router匹配路由时，对于相似路径匹配后，匹配成功后未停止匹配，按照上图路由规则，会匹配到两次PlanInputForm组件的渲染。

**参考**
重现步骤：
![image](https://user-images.githubusercontent.com/13513786/121650929-ab3d6a00-cacc-11eb-8445-df9e3c1227b2.png)

**预期行为**
只需要匹配一次

**可重现环境：**
 - 系统： macOS
 - 浏览器： chrome
 - HIUI 的版本：3.5.1-rc.9

**附加内容**
关于此问题的其它信息。

**Comment by wugaoliang1116** [comment]
https://github.com/hiui-group/classic-theme/issues/61

**Comment by solarjoker** [comment]
> **Bug 描述**
> react-router匹配路由时，对于相似路径匹配后，匹配成功后未停止匹配，按照上图路由规则，会匹配到两次PlanInputForm组件的渲染。
> 
> **参考**
> 重现步骤：
> ![image](https://user-images.githubusercontent.com/13513786/121650929-ab3d6a00-cacc-11eb-8445-df9e3c1227b2.png)
> 
> **预期行为**
> 只需要匹配一次
> 
> **可重现环境：**
> 
> * 系统： macOS
> * 浏览器： chrome
> * HIUI 的版本：3.5.1-rc.9
> 
> **附加内容**
> 关于此问题的其它信息。

我认为这并不是一个bug，因为在截图中 `/a/:id/layout/:layoutId` 包含了 `/a/create/layout/:layoutId` ，所以根据react-router，两个组件均匹配某个路径，所以都渲染是符合预期的。要解决你的问题可能需要你去调整你的path，比如通过正则排除掉create
