### ISSUE TITLE
Table 组件 非冻结列 th 和 td 数据没对齐

### ISSUE THREAD

**Issue by chownchen** [XiaoMi/hiui#1775]
**Bug 描述**
HIUI：3.6.1-rc.5

![image](https://user-images.githubusercontent.com/18654951/122005780-a3413b00-cde8-11eb-95fc-b244dc2e2227.png)

**Comment by wugaoliang1116** [comment]
该问题为，对columns中width属性设置问题。已兼容老 table。scrollWidth属性
