### ISSUE TITLE
Table，表头没对齐

### ISSUE THREAD

**Issue by orcjie** [XiaoMi/hiui#1794]
表格字段较多的情况下，左侧固定列，向右滑动，表头和列没有对齐

- [ ] 
![image](https://user-images.githubusercontent.com/23741640/122888265-460f3180-d374-11eb-9d3a-b4b840cbd82c.png)

**Comment by wugaoliang1116** [comment]
3.7.0-rc.1  请注意 冻结表格需要给宽度，并删除 scrollWidth 属性
