### ISSUE TITLE
Tabs嵌套使用，若设置不同type将会出现样式继承的问题

### ISSUE THREAD

**Issue by Walker-os** [XiaoMi/hiui#1841]
**Bug 描述**
两个不同type的Tabs嵌套使用，里面那个Tabs会继承外面那个的样式；

**参考**

**预期行为**
不同type的Tabs样式互不影响；

**截屏**
![image](https://user-images.githubusercontent.com/43165856/125574719-c53da445-5bc3-4326-bab2-87e78fca5a28.png)

**可重现环境：**
 - 系统： macOS 11.4
 - 浏览器：chrome9.1
 - HIUI 的版本： ^3.5.1-rc.9

**附加内容**

**Comment by solarjoker** [comment]
done
