### ISSUE TITLE
多选Select在data中设置disable时的一些逻辑差异优化

### ISSUE THREAD

**Issue by s952787097** [XiaoMi/hiui#1843]
**你期望的功能是否与某种使用上的困难相关？如果是请描述一下**
多选Select：
当data数据中包含disabled时，此项options被禁止修改，但是Select文本框默认选中值为该项options时，删除图标(x) 没有隐藏，因为其disabled所以不应该有可以修改该项options的任何操作。

同时当Select配置clearable时应只清除disabled以外的默认选中值，disabled的options是否显示在Select文本框中取决于是否是默认值或改变了Select默认选中值的数组

**描述你期待的解决方案**
无

**描述你考虑的其它形式**
无

**附加信息**
![image](https://user-images.githubusercontent.com/26595017/126277164-b41a733d-e857-4843-952d-f9e9f86777e0.png)

**Comment by solarjoker** [comment]
4.0已支持
