### ISSUE TITLE
Drawer 样式问题

### ISSUE THREAD

**Issue by c19354837** [XiaoMi/hiui#1948]
**Bug 描述**
Drawer 会在右侧加上一个阴影效果，及时 visible 为 false

**参考**
重现步骤：
1. 使用 Drawer 组件
2. 观察窗口右侧，会发现有一层阴影（如果不明显，可以多加几个 Drawer 组件）

**预期行为**
在 visible 为 false 时不展示阴影

**Comment by Flcwl** [comment]
@c19354837 good~

**Comment by Flcwl** [comment]
@c19354837 我们发现了这个问题，马上修复

**Comment by Flcwl** [comment]
@c19354837 `@hi-ui/hiui@3.8.1-rc`
