### ISSUE TITLE
文档补充-类型声明缺失

### ISSUE THREAD

**Issue by solarjoker** [XiaoMi/hiui#1964]
- [x]  TimePicker 缺失clearable 描述
- [x] `Modal.open` 缺失 `content` 描述

**Comment by yyf401238353** [comment]
- [ ] Modal 组件 缺失 type, visible
 - [ ] Table 组件 TableColumnItem 类型 sorter 的定义有问题
 - [ ] Input 组件 没有 autoFocus的定义

**Comment by yyf401238353** [comment]
-[ ]  Table 组件 rowSelection 属性 的 onChange的第一个参数类型应该为<string|number>[] 实际为string|number

**Comment by yyf401238353** [comment]
- [ ] Table 组件 expandRowKeys 类型只有number[] 不支持string[] 的id

**Comment by Flcwl** [comment]
[] 进度条的ts少了percent属性校验
