### ISSUE TITLE
input组件的placeholder没法动态更新

### ISSUE THREAD

**Issue by zhoushan1** [XiaoMi/hiui#1982]
**Bug 描述**
input组件的placeholder没法动态更新。

**参考**
重现步骤：
1. 使用 Input组件的placeholder属性
2. 动态变化placeholder的值

**预期行为**
placeholder值对应改变

**截屏**
如果方便的话可以提供一个截屏描述你的问题。

**可重现环境：**
 - 系统： [ macOS]
 - 浏览器： [chrome最新版]
 - HIUI 的版本： [3.7.1]

**Comment by Flcwl** [comment]
@zhoushan Done. @hi-ui/hiui@3.8.1-rc.5
