### ISSUE TITLE
SelectTree 支持自定义过滤

### ISSUE THREAD

**Issue by YuVincentxuan** [XiaoMi/hiui#2009]
**你期望的功能是否与某种使用上的困难相关？如果是请描述一下**
目前SelectTree组件的实时过滤效果存在这样一个问题：在子选项不匹配关键字的时候会导致子选项丢失。
![image](https://user-images.githubusercontent.com/32960222/142971306-799e4607-971d-4f96-8163-3927c3695a5f.png)

**描述你期待的解决方案**
支持用户自定义过滤方案（不限于高亮、实时过滤），
![image](https://user-images.githubusercontent.com/32960222/142971504-88d3cad8-fc99-47c9-ba04-d9202e36f04f.png)

**描述你考虑的其它形式**
可以提供参数去选择是否开启(高亮、过滤、过滤时是否过滤掉没有匹配上的子节点)

**附加信息**
无

**Comment by Flcwl** [comment]
@YuVincentxuan @hi-ui/hiui@3.9.0-rc.3 done
