### ISSUE TITLE
在多个下拉框中间插入一个下拉框会点击原来的某个下拉框展示会出现下拉框定位偏移的状况

### ISSUE THREAD

**Issue by Fang-fs** [XiaoMi/hiui#2011]
**Bug 描述**
在多个下拉框中间插入一个下拉框会点击原来的某个下拉框展示会出现下拉框定位偏移的状况

**参考**
重现步骤：
1. 使用 多个 Select 组件
2. 在多个select 中间动态插入一个select 下拉框 ，点击插入之前的某个 Select下拉框
4. 此时下拉框定位出现偏移

**预期行为**
下拉框定位不便宜
**截屏**
![image](https://user-images.githubusercontent.com/20946714/143182822-df6e79f7-fb2a-4d69-9851-5415400953dd.png)

**可重现环境：**
任何环境 任何浏览器

**附加内容**
关于此问题的其它信息。

**Comment by Flcwl** [comment]
@Fang-fs 嗨，图中哪个是动态的插入的？可以录个屏吗？

**Comment by Flcwl** [comment]
@Fang-fs next: 3.9.0-rc.2
