### ISSUE TITLE
Tree 树形组件性能问题

### ISSUE THREAD

**Issue by soleil0-0** [XiaoMi/hiui#2096]
**Bug 描述**
当节点数较多，如 2499 时。塞入数据后，树形组件会出现明显卡顿，约 2s。

**参考**
重现步骤：
1. 使用 Tree 组件
2. 设置 editable, data, expandedIds, checkedIds。data 塞入数据，约 2499 个节点
3. 设置数据的当下就会出现卡顿，外面设置的 loading 效果都会卡住。

**预期行为**
塞入数据后，不明显感知卡顿

**截屏**

**可重现环境：**
 - 系统：Win10, ArchLinux
 - 浏览器： Chrome
 - HIUI 的版本： 3.8.0

**附加内容**
关于此问题的其它信息。

**Comment by Flcwl** [comment]
@soleil0-0 这个问题会在 v4 进行优化，目前正在内测，正式发布时间待定，到时候会通知你
