### ISSUE TITLE
开发环境添加终端 log

### ISSUE THREAD

**Issue by bougieL** [XiaoMi/hiui#226]
- 添加 friendly-errors-webpack-plugin (参考 mirc)
- standard 整合进 ESLint
- stylelint 整合进 PostCSS
- 添加 eslint-loader
- 开发环境添加 postcss-loader，可在终端看见不规范的样式错误

**Comment by solarjoker** [comment]
赞成，加了 eslint 是不是可以直接把 standard 去了，直接我们就用 recommend 就可以了吧。另外 prettier 也可以整合进 eslint

**Comment by sivan** [comment]
@bougieL standard 整合进 ESLint 的目的是？

**Comment by bougieL** [comment]
> @bougieL standard 整合进 ESLint 的目的是？

配合 `eslint-loader` 和 `friendly-errors-webpack-plugin`， 可在开发时，终端实时展示不符合 standard 规范的错误 :milk_glass:
