### ISSUE TITLE
Cascader组件displayRender会触发两次的问题 【Bug】

### ISSUE THREAD

**Issue by White-Lu** [XiaoMi/hiui#246]
Cascader组件的displayRender方法会执行两次

**Comment by solarjoker** [comment]
@White-Lu 方便提供一下你使用的版本号和执行两次的截图吗？

**Comment by White-Lu** [comment]
<img width="432" alt="WechatIMG89" src="https://user-images.githubusercontent.com/22442934/58602017-c6f6be80-82bd-11e9-818a-456370f3da39.png">

**Comment by White-Lu** [comment]
![image](https://user-images.githubusercontent.com/22442934/58602084-0d4c1d80-82be-11e9-883a-64b6d26ae96b.png)

**Comment by White-Lu** [comment]
使用这个组件，初始化的时候，会执行两次displayRender
