### ISSUE TITLE
考虑使用 CSS Variables 实现配色主题等功能

### ISSUE THREAD

**Issue by sivan** [XiaoMi/hiui#256]
特性兼容度尚可，IE 有腻子 https://github.com/jhildenbiddle/css-vars-ponyfill
使用 CSS Variables 可以大幅减少配色主题所需要的代码。

**Comment by sivan** [comment]
https://codyhouse.co/blog/post/css-custom-properties-vs-sass-variables

**Comment by LIAOTOW** [comment]
可以使用css-var的垫片 https://github.com/jhildenbiddle/css-vars-ponyfill

**Comment by solarjoker** [comment]
support in 3.0.0
