### ISSUE TITLE
List.Item avatar 允许使用 React.ReactNode

### ISSUE THREAD

**Issue by sgpublic** [XiaoMi/hiui#2574]
**你期望的功能是否与某种使用上的困难相关？如果是请描述一下**
我的列表里头像没有图片，于是按照用户名生成由一到两个大写字母作为头像，但是 `List.Item` 的 `avatar` 只允许 `string` 作为 `img` 的 `src`

**描述你期待的解决方案**
如题，这样就可以在 `avatar` 使用 [Avatar](https://xiaomi.github.io/hiui/components/avatar/) 组件

**Comment by zyprepare** [comment]
收到，我们计划最近2周来支持这个功能。

**Comment by zyprepare** [comment]
修复版本 @hi-ui/list@4.0.9
