### ISSUE TITLE
Tabs 标签切换样式抖动

### ISSUE THREAD

**Issue by c19354837** [XiaoMi/hiui#260]
在 [官方文档 - tabs](https://xiaomi.github.io/hiui/#/zh-CN/docs/tabs) 中，「带描述信息的标签」以及「按钮式标签」小节，切换 tab 会有样式抖动，表现在整体布局右移或者文字下移

**Comment by bougieL** [comment]
get

**Comment by c19354837** [comment]
文档上效果还是之前的，大概什么时候能发布新版本

**Comment by bougieL** [comment]
等下个正式版
