### ISSUE TITLE
actionRender自定义按钮

### ISSUE THREAD

**Issue by pzyg** [XiaoMi/hiui#2694]
希望可以完善示例的自定义按钮功能，actionRender的参数props为什么没有onRemove事件

**Comment by zyprepare** [comment]
您好，是说的哪个组件，哪个版本？

**Comment by pzyg** [comment]
你好，我想咨询一下这个上传组件自定义按钮之后怎么实现删除功能？



***@***.***
 
发件人： zhouyun
发送时间： 2023-12-15 11:25
收件人： XiaoMi/hiui
抄送： 张宇; Author
主题： Re: [XiaoMi/hiui] actionRender自定义按钮 (Issue #2694)
您好，是说的哪个组件，哪个版本？

**Comment by zyprepare** [comment]
可以使用 Upload 组件支持受控的 fileList 参数，然后在 actionRender 里面自定义的元素上绑定 onClick 事件，在该事件回调中去修改 fileList 的数据。
另外，这个地方的示例我们也优化下！感谢反馈！
