### ISSUE TITLE
Delete value problem about DataPicker range

### ISSUE THREAD

**Issue by chownchen** [XiaoMi/hiui#339]
After selecting the date, click'X'to delete the selected date, click the selection box again, trigger the onChange event, return to the last selected event, and the date list still shows the last selected date.

![1741561638722_ pic_hd](https://user-images.githubusercontent.com/18654951/60268328-c41fd580-991e-11e9-86e2-2eaf3bc7ea7b.jpg)

**Comment by bougieL** [comment]
中文说明：
`date-picker` focus 和 blur 会触发 onChange 事件。
而且没有选择值时 onChange 回调值不对，没选择值时应回调 null
