### ISSUE TITLE
Input标签type="textarea" 拖动的时候，样式问题。1.5.0的版本

### ISSUE THREAD

**Issue by WittyColor** [XiaoMi/hiui#342]
正常的时候是这样
![image](https://user-images.githubusercontent.com/22442934/60476212-4573c100-9cad-11e9-9ff3-d1faed10a0e6.png)
但是我拖动的时候，就是这样子了，样式错乱了。我往下拖
![image](https://user-images.githubusercontent.com/22442934/60476231-64725300-9cad-11e9-8dfe-b558cfc565bb.png)
或者我往上面拖
![image](https://user-images.githubusercontent.com/22442934/60476251-7653f600-9cad-11e9-8c68-d6608b48ca05.png)

**Comment by solarjoker** [comment]
稳定版本中已经修复
