### ISSUE TITLE
Table 组件重构已满足新功能需求

### ISSUE THREAD

**Issue by sivan** [XiaoMi/hiui#359]
一言难尽。

**Comment by solarjoker** [comment]
现有功能基础上进行大幅优化  
- 视觉交互重新调整
  - 支持树形表格
  - 支持列对齐
  - 支持动态控制列宽
  - 支持标准模式
  - 支持控制行高亮
  - 支持控制列高亮
  - 优化了列冻结
  - 优化了表头吸顶
  - 优化了列调整，支持调整列的顺序
  - api 优化
