### ISSUE TITLE
增加 ECharts 样式集成

### ISSUE THREAD

**Issue by sivan** [XiaoMi/hiui#388]
**你期望的功能是否与某种使用上的困难相关？如果是请描述一下**
目前无内置的图表组件的文档说明如果方便实现报表页面

**描述你期待的解决方案**
在文档和项目内完成对 ECharts 的集成和主题设置，而不需要用户自己去引用和学习相关文档的使用。

**Comment by solarjoker** [comment]
support in 3.0.0
