### ISSUE TITLE
表格分页

### ISSUE THREAD

**Issue by longquanwu** [XiaoMi/hiui#396]
**Bug 描述**
表格类自带的分页 pagination， 切换页码后一直选中第一页。
之前1.3.2版本貌似没有问题，更新至1.5.2版本就会出现这个bug

**参考**
重现步骤：
1、使用Table组件展示数据，设置pagination属性。
2、当在页面点击第二页时，页面刷新后 还是默认选中第一页（期望应选中第二页）

**预期行为**
当点击第二页，页面数据重新加载后，期望应选中第二页

**截屏**

**可重现环境：**
 - 系统： [macOS]
 - 浏览器： [chrome, safari]
 - HIUI 的版本： [1.5.2]

**附加内容**

**Comment by solarjoker** [comment]
使用 defaultCurrent 替代原 current
