### ISSUE TITLE
Button不能自定义图标？

### ISSUE THREAD

**Issue by An-DJ** [XiaoMi/hiui#428]
**你期望的功能是否与某种使用上的困难相关？如果是请描述一下**
有需求使用Button组件，但是似乎Button组件的Icon只能使用默认给出的图标库的几种图标，不能使用自定义的图片作为图标。

**描述你期待的解决方案**
扩充图标库只能暂时解决，希望可以让Icon可以使用自定义的图标。

**描述你考虑的其它形式**
没有了，应该实现起来不难。

**附加信息**
希望贵团队能够纳入考虑！谢谢！

**Comment by sivan** [comment]
@An-DJ 目前除了 `<Button type="primary" icon="plus">创建客户</Button>` 这种方式引入官方自带的图标，也可以手动引入想要的图标，然后使用 `<Button type="primary"><MyCustomIcon /> 创建客户</Button>` 嵌套来实现。

**Comment by An-DJ** [comment]
@sivan 谢谢！嵌套可以实现，不过之前遇到了样式的问题，但已经使用了CSS进行调整。效果还不错
