### ISSUE TITLE
Table组件FixtTopBug

### ISSUE THREAD

**Issue by letyougo** [XiaoMi/hiui#429]
**Bug 描述**
清晰简洁的描述 bug 内容。

**参考**
重现步骤：
1. 使用 Table 组件
2. 配置 'fixTop后.'
3. 按钮组件区不会被遮挡

**预期行为**
清晰简洁的描述应当产生的效果。

**截屏**
如果方便的话可以提供一个截屏描述你的问题。

**可重现环境：**
 - 系统： [比如 macOS]
 - 浏览器： [比如 chrome, safari]
 - HIUI 的版本： [比如 1.3.6]

**附加内容**
关于此问题的其它信息。

**Comment by zhan8863** [comment]
![image](https://user-images.githubusercontent.com/10891518/61503773-8ee14180-aa0b-11e9-9020-0bf8f4499635.png)

**Comment by sivan** [comment]
回滚，受 radio button 功能影响，不能单纯的删除 button 的 position: relative; 属性

**Comment by solarjoker** [comment]
2.x 不修了，3.x 中解决
