### ISSUE TITLE
官网文档更新日志BUG

### ISSUE THREAD

**Issue by letyougo** [XiaoMi/hiui#435]
**Bug 描述**
官网文档的更新日志和github更新日志不同步
### 官网文档
![55391563782761_ pic_hd](https://user-images.githubusercontent.com/12511665/61624005-5743f500-acaa-11e9-9182-e929a0e449d3.jpg)

### github
![55411563782779_ pic_hd](https://user-images.githubusercontent.com/12511665/61624011-590db880-acaa-11e9-9590-ed47b508d97e.jpg)

**Comment by sivan** [comment]
fixed
