### ISSUE TITLE
单测问题整理

### ISSUE THREAD

**Issue by solarjoker** [XiaoMi/hiui#439]
- [x] Badge 组件
![911563869019_ pic_hd](https://user-images.githubusercontent.com/13705393/61694717-a2224300-ad64-11e9-912f-6e3715add0d2.jpg)

**Comment by snake89322** [comment]
@solarjoker bugs：

FIXME:

- [ ] Badge: Badge.js #34 typeof +content === 'number' always be true

- [ ] Button: Button.js Props 'target' not be added in element <a />

NOTE:

- [ ] Cascader: Cascader.js Props 'fieldNames' is inconsistent with the document

- [ ]  Cascader: Cascader.js Props 'emptyContent' is not up to expect
