### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by ColdDay** [XiaoMi/hiui#44]
1：上传图标没对齐，头像上传裁剪区域没法拖动
![image](https://user-images.githubusercontent.com/16549553/50134842-f7790c00-02cc-11e9-80f5-5bccef5685e2.png)
![image](https://user-images.githubusercontent.com/16549553/50134853-0364ce00-02cd-11e9-9026-62eefadd1561.png)
![image](https://user-images.githubusercontent.com/16549553/50134855-0b247280-02cd-11e9-8925-dff32214c9cd.png)
![image](https://user-images.githubusercontent.com/16549553/50134859-0f509000-02cd-11e9-8363-d2ceb01a4fbc.png)
2:
model弹出框没有加渐显动画
3：校验颜色不一样
![image](https://user-images.githubusercontent.com/16549553/50134846-ff38b080-02cc-11e9-977a-05a0c9626288.png)
4：输入框没内容还显示清空
![image](https://user-images.githubusercontent.com/16549553/50134854-05c72800-02cd-11e9-8018-a1c7dcdc3366.png)

**Comment by MrZhang123** [comment]
帮顶

**Comment by solarjoker** [comment]
done in 1.5.3
