### ISSUE TITLE
feat(Button)/ add native type attr for Button

### ISSUE THREAD

**Issue by Flcwl** [XiaoMi/hiui#442]
**你期望的功能是否与某种使用上的困难相关？如果是请描述一下**

为Button组件添加原生 `type` 属性（（`submit`、`button`、`reset`）支持，在不使用Form表单组件的情况下，也能合适地使用 Button 组件，完善体验。

**描述你期待的解决方案**

鉴于Button组件 `type` 属性作为主题配置（`'primary' | 'line' | 'success' | 'danger' | 'default'`），需要另外命名使用原生 `type` 属性，参考其它库设计，可用 `htmlType` 为其命名。

**描述你考虑的其它形式**

使用Form表单组件，参考Demo可以满足提交重置等功能，但页面不支持 `enter` 键操作提交，降低了页面易用性。

**附加信息**

Null

**Comment by solarjoker** [comment]
暂时先不考虑支持
