### ISSUE TITLE
Table组件

### ISSUE THREAD

**Issue by 1563610087** [XiaoMi/hiui#474]
**你期望的功能是否与某种使用上的困难相关？如果是请描述一下**
现在的项目有个需求，当鼠标悬停到table的某一行，可以在下面有一个信息框，可以展示出当前行的所有信息，目前这个需求实现 比较麻烦，hiui没有这方面的功能

**描述你期待的解决方案**
期望hi UI可以考虑一下这个功能。

**描述你考虑的其它形式**
清晰简洁的描述你考虑过的其它解决方式或实现功能。

**附加信息**
关于你的功能需求的任何附加信息或截图说明等。

**Comment by sivan** [comment]
@1563610087  「展示出当前行的所有信息」是指隐藏列的内容也展示，如果是浮层展示，占用空间太大。可否用这种 https://xiaomi.github.io/hiui/zh-CN/docs/table#%E6%89%A9%E5%B1%95%E4%B8%80%E8%A1%8C 然后把展开区域换成你说的信息？
