### ISSUE TITLE
Tree: 组件自带的拖拽无法与其他的三方工具比如react-dnd一起使用

### ISSUE THREAD

**Issue by earnest1997** [XiaoMi/hiui#554]
**Bug 描述**
清晰简洁的描述 bug 内容。

**参考**
重现步骤：
1. 使用 xx 组件
2. 点击 '....'
3. 触发 '....'
4. 此时控制台开始抛错

**预期行为**
清晰简洁的描述应当产生的效果。

**截屏**
如果方便的话可以提供一个截屏描述你的问题。

**可重现环境：**
 - 系统： [比如 macOS]
 - 浏览器： [比如 chrome, safari]
 - HIUI 的版本： [比如 1.3.6]

**附加内容**
关于此问题的其它信息。

**Comment by solarjoker** [comment]
使用内部暴露的即可
import withDragDropContext from '@hi-ui/hiui/es/lib/withDragDropContext'
