### ISSUE TITLE
清空搜索条件后，树状结构分类不可收回

### ISSUE THREAD

**Issue by Enzyme-ZZ** [XiaoMi/hiui#561]
**Bug 描述**
清空搜索条件后，树状结构分类全部展开且不可收回

**参考**
重现步骤：
1. 同时支持勾选和搜索的树结构
2. 全部展开树节点，进行搜索，然后清空搜索条件
3. 点击树节点收回
4. 无响应，树节点不可回收

**预期行为**
节点回收

**截屏**
如果方便的话可以提供一个截屏描述你的问题。

**可重现环境：**
 - 系统：macOS
 - 浏览器：chrome
 - HIUI 的版本：2.0.2

**附加内容**
关于此问题的其它信息。

**Comment by solarjoker** [comment]
#601

**Comment by chownchen** [comment]
已验证
