### ISSUE TITLE
Switch 组件存在重复渲染的问题

### ISSUE THREAD

**Issue by MagicPigtail** [XiaoMi/hiui#564]
**Bug 描述**
在 Swich 组件的onChange回调中调用setState方法会导致页面渲染两遍，即使是页面依赖的数据不在setState改变的值中。

**参考**
重现步骤：
1. 使用 Switch 组件
2. 点击 '组件'
3. 触发 '状态切换' --> 'onChange回调' --> 'setState'方法
4. 页面强制渲染两遍

**预期行为**
页面是否重新渲染根据所依赖的数据是否改变，若改变，只渲染一遍。

**截屏**
`import React from 'react'
import Switch from '@hi-ui/hiui/es/switch'
import Button from '@hi-ui/hiui/es/button'

class Demo extends React.Component {
  constructor (props) {
    super(props)
    this.handleChange = this.handleChange.bind(this)
    this.state = {
      checked: true,
      disabled: true,
      list1:['1','2','3']
    }
  }
  onChange (status) {
    console.log(status)
  }
  handleChange () {
    let list1 = [...this.state.list1]
    console.log(123)
    this.forceUpdate()
  }
  render () {
    return (
      <div>
        <p>自定义内容</p >
        <Switch content={['ON', 'OFF']} onChange={this.handleChange}/>
      </div>
    )
  }
}`

**可重现环境：**
 - 系统： macOS]
 - 浏览器： chrome
 - HIUI 的版本： 2.0.5

**附加内容**

**Comment by solarjoker** [comment]
请问是 Tag 组件还是 Switch 组件？

**Comment by MagicPigtail** [comment]
抱歉，是Switch，已经跟hiui的支持报备了，该组件的onChange回调中必须要传入checked参数表示当前状态，建议将该回调做出一个高阶函数，避免checked参数的污染

**Comment by chownchen** [comment]
该问题因为checked属性没有绑定到state上，当点击swtich组件时，该组件所在页面修改其他state，触发了rerender，导致switch被初始化，默认为unchecked，onChange事件会被触发两次。
该问题已经通过给Switch的checked属性绑定state，onChange触发后更新checked值，可以正常操作
