### ISSUE TITLE
Tree控件的搜索功能需要所有节点都有唯一ID

### ISSUE THREAD

**Issue by sherry2014** [XiaoMi/hiui#571]
**Bug 描述**
清晰简洁的描述 bug 内容。

**参考**
重现步骤：
1. 使用 xx 组件
2. 点击 '....'
3. 触发 '....'
4. 此时控制台开始抛错

**预期行为**
清晰简洁的描述应当产生的效果。

**截屏**
如果方便的话可以提供一个截屏描述你的问题。

**可重现环境：**
 - 系统： [比如 macOS]
 - 浏览器： [比如 chrome, safari]
 - HIUI 的版本： [比如 1.3.6]

**附加内容**
关于此问题的其它信息。

**Comment by solarjoker** [comment]
请详细描述一下你的诉求～
