### ISSUE TITLE
Tree 清除搜索条件后无法收缩

### ISSUE THREAD

**Issue by c19354837** [XiaoMi/hiui#599]
**Bug 描述**
Tree 清除搜索条件后无法收缩

**版本**
HIUI 2.1.2

**重现步骤**
1. 启用搜索功能
2. 输入搜索条件（可匹配到子元素）
3. 清除搜索条件
4. 点击收缩按钮

**期望**
节点正常收起

**实际**
点击无效，多次点击后才能收起

**Comment by solarjoker** [comment]
#561
