### ISSUE TITLE
Form表单1.5 升2.0兼容问题

### ISSUE THREAD

**Issue by chownchen** [XiaoMi/hiui#608]
**Bug 描述**
FormItem 中的prop得改为field
- this.form.validate 得改为 this.form.current.validate

**参考**
重现步骤：
1. 使用 xx 组件
2. 点击 '....'
3. 触发 '....'
4. 此时控制台开始抛错

**预期行为**
清晰简洁的描述应当产生的效果。

**截屏**
如果方便的话可以提供一个截屏描述你的问题。

**可重现环境：**
 - 系统： [比如 macOS]
 - 浏览器： [比如 chrome, safari]
 - HIUI 的版本： [比如 1.3.6]

**附加内容**
关于此问题的其它信息。

**Comment by bougieL** [comment]
用回调函数声明的 ref 用 this.form.validate()，用 createRef() 声明的 ref 用 this.form.current.validate()，参考 https://zh-hans.reactjs.org/docs/refs-and-the-dom.html#accessing-refs
