### ISSUE TITLE
【1.5 -> 2.x升级不兼容】Alert组件，v1.5中的message属性被v2.x中的title取代，升级之后message和title错乱，导致样式错乱

### ISSUE THREAD

**Issue by Gy-gY** [XiaoMi/hiui#617]
**Bug 描述**
个人认为是1.5版本设计属性名称的时候出错，想再2.x版本中纠正，2.x中增加了title属性取代1.5中的message，同时保留了message，但message的意义已经不是1.5版本中的message了

**Comment by solarjoker** [comment]
FAQ
