### ISSUE TITLE
Switch 组件受控问题

### ISSUE THREAD

**Issue by bougieL** [XiaoMi/hiui#633]
**Bug 描述**
外部改变 Switch 组件的 checked 状态会触发 Switch 的 onChange 事件

**可重现环境**
 - HIUI 的版本： 2.2.0

应用 defaultChecked 和 checked 做区分

**Comment by solarjoker** [comment]
2.x 暂不支持

**Comment by Flcwl** [comment]
不受控吗？

**Comment by solarjoker** [comment]
3.x 中已解决
