### ISSUE TITLE
Select组件id选择导致图中错误

### ISSUE THREAD

**Issue by chownchen** [XiaoMi/hiui#646]
**Bug 描述**
api：
![image](https://user-images.githubusercontent.com/18654951/64509924-63941800-d313-11e9-963d-e5b126845652.png)

警告图：
![image](https://user-images.githubusercontent.com/18654951/64509924-63941800-d313-11e9-963d-e5b126845652.png)

重现步骤：
右边的报错 我打开下拉框会出现一次 然后鼠标滑动到某个选项上也会出现
（海外组-李云帆）
**参考**
重现步骤：
1. 使用 xx 组件
2. 点击 '....'
3. 触发 '....'
4. 此时控制台开始抛错

**预期行为**
清晰简洁的描述应当产生的效果。

**截屏**
如果方便的话可以提供一个截屏描述你的问题。

**可重现环境：**
 - 系统： [比如 macOS]
 - 浏览器： [比如 chrome, safari]
 - HIUI 的版本： [比如 1.3.6]

**附加内容**
关于此问题的其它信息。

**Comment by solarjoker** [comment]
#649
