### ISSUE TITLE
Table 组件报警告如下 A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can. If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead. React was passed "javascript:void(0)"

### ISSUE THREAD

**Issue by chownchen** [XiaoMi/hiui#656]
使用如下
<Table
                        size={'mini'}
                        columns={this.columns}
                        striped
                        data={this.props.data.records || []}
                        pagination={{
                            pageSize: parseInt(this.props.data.size || 12),
                            total: parseInt(this.props.data.total || 0),
                            current:parseInt(this.props.data.current || 1),
                            onChange: (page, pre, size) => {
                                this.setState(
                                    {
                                        page : page
                                    }, () => {
                                        this.fetchData()
                                    })
                            }
                        }}
                    />

**预期行为**
清晰简洁的描述应当产生的效果。

**截屏**
如果方便的话可以提供一个截屏描述你的问题。

**可重现环境：**
 - 系统： [比如 macOS]
 - 浏览器： [比如 chrome, safari]
 - HIUI 的版本： [比如 1.3.6]

**附加内容**
关于此问题的其它信息。

**Comment by solarjoker** [comment]
not a problem
