### ISSUE TITLE
add `onClose` callback as a param for `Notification.open({...})` way

### ISSUE THREAD

**Issue by Flcwl** [XiaoMi/hiui#678]
你期望的功能是否与某种使用上的困难相关？如果是请描述一下

如附加信息图描述，我想使用 `notifyCnt`做信号量，封装使用 `Notification.open`，一个页面只能生产消费一个 `notification`实例。但是发现 `onClose` 传进去用不了，求改进、、、thx.

描述你期待的解决方案

为 `Notification` 组件的 单例使用方式`Notification.open({ key, type, title, content, closesable, confirmText, onConfirm, size, duration })` 添加 `onClose` 回调函数。

描述你考虑的其它形式

自己添加 `settimeout(fn, duration)` 执行 `onCLose`时要做的事情

附加信息

![image](https://user-images.githubusercontent.com/26050644/65386226-43307880-dd6b-11e9-85d5-a5d71796f79c.png)

**Comment by bougieL** [comment]
自动关闭时触发 onClose

**Comment by bougieL** [comment]
会触发
