### ISSUE TITLE
Select 选择器

### ISSUE THREAD

**Issue by duanwenxiang** [XiaoMi/hiui#723]
**Bug 描述**
受控组件后，点击清除，会展开选择列表，而且数据没有被清除，再次点击清除才会被清除

**截屏**
![image](https://user-images.githubusercontent.com/46153686/66795349-ee7db900-ef36-11e9-98f7-815593c55704.png)
![image](https://user-images.githubusercontent.com/46153686/66795365-f9384e00-ef36-11e9-8b30-4a71b294ddc4.png)
![image](https://user-images.githubusercontent.com/46153686/66795374-fdfd0200-ef36-11e9-8ee1-8c6194dce90d.png)

**可重现环境：**
 - HIUI 的版本： 2.5.0

**Comment by solarjoker** [comment]
受控时，清除事件也需要自己在onChange 中同步，比如点击清除按钮，你需要在onChange 中将Select 的value 设置为空数组

**Comment by solarjoker** [comment]
NOT A PROBLEM
